# Generated by Django 2.2.5 on 2019-10-24 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='First_Name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Last_Name',
            new_name='age',
        ),
    ]
