# Generated by Django 2.2.5 on 2019-10-25 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20191024_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='age',
            new_name='city',
        ),
    ]
